---
- name: Download do WordPress
  get_url: 
    url=https://wordpress.org/latest.tar.gz 
    dest=/tmp/wordpress.tar.gz
    validate_certs=no

- name: Extracting the wordpress
  unarchive: src=/tmp/wordpress.tar.gz dest=/tmp/ copy=no
 
- name: Moving archives wordpress
  shell: mv /tmp/wordpress/* /var/www/html/

- name: Removing archives wordpress
  shell: cd /tmp && rm -rf wordpress.tar.gz

- name: Template archive wp-config
  template:
     src: wp-config.php.j2
     dest: /var/www/html/wp-config.php

- name: Start and enable boot php-fpm
  service: name=php-fpm state=started enabled=yes

