--- 
- name: Update apt cache
  apt: update_cache=yes cache_valid_time=3600

- name: Installing dependency wordpress
  apt: name={{ item }} state=present
  with_items:
    - apache2
    - mysql-server
    - php7.2-mysql
    - php7.2
    - libapache2-mod-php7.2
    - python-mysqldb

  
 

