- hosts: all
  gather_facts: False
  become: yes

  tasks:
  - name: Install python 2
    raw: test -e /usr/bin/python || (apt -y update && apt install -y python-minimal)
  become: yes

- name: Applying installation and dependency 
  hosts: localhost
  become: yes 
   
  roles:
     - server

- name: Applying installation php
  hosts: localhost
  become: yes
  
  roles:
     - php

- name: Applying database configuration
  hosts: localhost
  become: yes

  roles:
     - mysql

- name: Applying Wordpress installation and configuration
  hosts: localhost
  become: yes

  roles:
     - wordpress


